# Generated by Django 3.2.3 on 2021-06-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20210531_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='no_of_owners',
            field=models.IntegerField(),
        ),
    ]
